{% set version = "1.9.30" %}

package:
  name: boto3
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/b/boto3/boto3-{{ version }}.tar.gz
  sha256: 3b782268ebf09ae6ea811ba8b8bdfc38a58d27f4f7fc554658f07c11ddc4165d

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - botocore >=1.12.29,<1.13.0
    - jmespath >=0.7.1,<1.0.0
    - s3transfer >=0.1.10,<0.2.0

test:
  imports:
    - boto3
    - boto3.docs
    - boto3.dynamodb
    - boto3.ec2
    - boto3.resources
    - boto3.s3

about:
  home: https://aws.amazon.com/sdk-for-python
  license: Apache 2.0
  license_file: LICENSE
  license_family: Apache
  summary: Amazon Web Services SDK for Python
  description: |
    Boto3 makes it easy to integrate you Python application, library or script
    with AWS services. It allows Python developers to write softare that makes
    use of services like Amazon S3 and Amazon EC2.
  doc_url: https://boto3.readthedocs.org
  doc_source_url: https://github.com/boto/boto3/blob/develop/README.rst
  dev_url: https://github.com/boto/boto3

extra:
  recipe-maintainers:
    - proinsias
    - tkelman
    - ocefpaf
