{% set name = "boto3" %}
{% set version = "1.7.75" %}
{% set sha256 = "9ed1461b5b5566100eaaaf9406111e0613cd42e580ed737d9ec4224c31cad1f8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
  run:
    - python
    - botocore >=1.10.75,<1.11.0
    - jmespath >=0.7.1,<1.0.0
    - s3transfer >=0.1.10,<0.2.0

test:
  imports:
    - boto3
    - boto3.docs
    - boto3.dynamodb
    - boto3.ec2
    - boto3.resources
    - boto3.s3

about:
  home: http://aws.amazon.com/sdk-for-python/
  dev_url: https://github.com/boto/boto3
  doc_url: https://boto3.readthedocs.org
  license: Apache 2.0
  license_file: LICENSE
  license_family: Apache
  summary: Amazon Web Services SDK for Python
  description: |
    Boto3 makes it easy to integrate you Python application, library or script
    with AWS services. It allows Python developers to write softare that makes
    use of services like Amazon S3 and Amazon EC2.
  doc_url: https://boto3.readthedocs.org
  doc_source_url: https://github.com/boto/boto3/blob/develop/README.rst
  dev_url: https://github.com/boto/boto3

extra:
  recipe-maintainers:
    - proinsias
    - tkelman
