{% set version = "1.36.20" %}
{% set hash = "4a27ffc0543c2a429600542047f00c6a1e95270139d36d8cc636e9cc9a78b835" %}

package:
  name: boto3
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/b/boto3/boto3-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - botocore >=1.36.20,<1.37.0
    - jmespath >=0.7.1,<2.0.0
    - s3transfer >=0.11.0,<0.12.0

test:
  imports:
    - boto3
    - boto3.docs
    - boto3.dynamodb
    - boto3.ec2
    - boto3.resources
    - boto3.s3
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://aws.amazon.com/sdk-for-python
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  summary: Amazon Web Services SDK for Python
  description: |
    Boto3 makes it easy to integrate you Python application, library or script
    with AWS services. It allows Python developers to write softare that makes
    use of services like Amazon S3 and Amazon EC2.
  doc_url: https://boto3.readthedocs.org
  doc_source_url: https://github.com/boto/boto3/blob/develop/README.rst
  dev_url: https://github.com/boto/boto3

extra:
  recipe-maintainers:
    - tkelman
    - ocefpaf
