{% set version = "1.9.196" %}
{% set vmajor,vminor,vpatch = version.split('.') %}
# ALWAYS DOUBLE-CHECK THESE OFFSETS AGAINST UPSTREAM setup.py
{% set botocore_major = vmajor | int + 0 %}
{% set botocore_minor = vminor | int + 3 %}
{% set botocore_patch = vpatch | int + 0 %}
{% set botocore_min = botocore_major ~ '.' ~ botocore_minor ~ '.' ~ botocore_patch %}
{% set botocore_max = botocore_major ~ '.' ~ (botocore_minor + 1) ~ '.0' %}

package:
  name: boto3
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/b/boto3/boto3-{{ version }}.tar.gz
  sha256: f80634723c7fb94daa4ef3a9706d6d9552a5da6c2329327cd86884c76cf6e95f

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - botocore >={{ botocore_min }},<{{ botocore_max }}
    - jmespath >=0.7.1,<1.0.0
    - s3transfer >=0.2.0,<0.3.0

test:
  imports:
    - boto3
    - boto3.docs
    - boto3.dynamodb
    - boto3.ec2
    - boto3.resources
    - boto3.s3

about:
  home: https://aws.amazon.com/sdk-for-python
  license: Apache 2.0
  license_file: LICENSE
  license_family: Apache
  summary: Amazon Web Services SDK for Python
  description: |
    Boto3 makes it easy to integrate you Python application, library or script
    with AWS services. It allows Python developers to write softare that makes
    use of services like Amazon S3 and Amazon EC2.
  doc_url: https://boto3.readthedocs.org
  doc_source_url: https://github.com/boto/boto3/blob/develop/README.rst
  dev_url: https://github.com/boto/boto3

extra:
  recipe-maintainers:
    - proinsias
    - tkelman
    - ocefpaf
