travis:
  secure:
    BINSTAR_TOKEN: k3r467d+ANyHCBEDj8alpr8e444EI5TakEnxqFzBW1hpFZPpT8FeTe7hOsOY2/WydkZMQN6jWJkczwjgjHkjGqPgF/t/iktjuDfLZfvPrdngfLEGo/tbotCTdrcQOb0G/FURkf3siBO4EyxVeK5KF3hXOewAO9/2+qRf1guq8Pd//P2zmItFRXwOUB/8jVqs3hCBVHNLfDFxmXUwFHXMDAZnaHXgL73Ojw9e4zn00VTrBmCeE+geUywo0h0UhOQ5hNVqcJXLunRxdG2xKevjoIX+r88szfHqqvU/tJ3XHbUHKOieodbfDXSHL8I1NE5dYDdvxMi6ejQJc6yn/7h+2gVQBiYazuTcmXgeAs+lSfdblY2umHgn5IdOeEc6pi/L+XHrvpc4QeOFkoC+R3X6OkZZ1UcZoSHDzzIbbOaWrwDjvN8drTDzzb1riFb8oDp5oCrww9Q8SYXLbPRZ/7kIuMmS4SHIYwIoBmtPFTm7/SHXzaNA76f1QlpieTkjXwvbbvYHgwQQi+XHfB2YQO3gBDsKUC8Jzz1EcXCAagqpxXwbD1pSfngpRyuj9GgOFBwf0OD/IBJJD3reaCYiw3l118l2uZKFGJRzvtph6vgqPTPoQeGbdoK10PXH05p9voHpe9QJjj1iGXmGHm8K1xfGI7Obe2HegBD+w6/4h00QVTw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  linux: azure
